// Command docs-gen generates the CLI reference pages for the docs site from
// the frames CLI's cobra command tree (cli/cmd). Run it from the repository
// root:
//
//	go run ./tools/docs-gen
//
// Output is deterministic: running it twice in a row produces byte-identical
// files, so the generated pages can be committed and the docs site can build
// from them without needing Go at all.
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"

	"github.com/nebari-dev/nebari-frames/cli/cmd"
)

// outDir is relative to the repository root, matching how this tool is
// documented to be invoked (`go run ./tools/docs-gen` from the repo root).
const outDir = "docs/site/src/content/docs/reference/cli"

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "docs-gen:", err)
		os.Exit(1)
	}
}

func run() error {
	root := cmd.NewRootCmd()
	disableAutoGenTag(root)
	// cobra/doc does not initialize the --version flag on its own (only
	// Execute() does), so without this the generated root page would omit a
	// flag the CLI genuinely accepts.
	root.InitDefaultVersionFlag()

	// Clear the directory first so a renamed or removed command does not
	// leave behind a stale page.
	if err := os.RemoveAll(outDir); err != nil {
		return fmt.Errorf("clear output dir: %w", err)
	}
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return fmt.Errorf("create output dir: %w", err)
	}

	identity := func(s string) string { return s }
	if err := doc.GenMarkdownTreeCustom(root, outDir, frontmatter, identity); err != nil {
		return fmt.Errorf("generate cli docs: %w", err)
	}
	return nil
}

// disableAutoGenTag turns off cobra/doc's "Auto generated by spf13/cobra on
// <date>" footer throughout the tree, so the generated pages are
// byte-identical across runs regardless of what day they are generated on.
func disableAutoGenTag(c *cobra.Command) {
	c.DisableAutoGenTag = true
	for _, sub := range c.Commands() {
		disableAutoGenTag(sub)
	}
}

// frontmatter adds the Starlight frontmatter that cobra/doc does not produce
// on its own. The title is recovered from the generated filename, which
// cobra derives from the command's full path, e.g. "frames_auth_login.md"
// becomes the title "frames auth login".
func frontmatter(filename string) string {
	name := strings.TrimSuffix(filepath.Base(filename), ".md")
	title := strings.ReplaceAll(name, "_", " ")
	return fmt.Sprintf("---\ntitle: %s\n---\n\n", title)
}
